---
- name: Launch Prudential-DevServer | create dev server instance
  local_action:
          module: ec2
          region: "{{ vpc_region }}"
          group: "{{ web_security_groups[0].sg_name }}"
          keypair: "{{ key_name }}"
          instance_type: "{{ instance_type }}"
          image: "{{ image_id }}"
          wait: true
          vpc_subnet_id: "{{ public_subnet }}"
          assign_public_ip: yes
          wait_timeout: 600
          instance_tags:
                  Name: prudential_dev
                  Environment: dev
  register: web

- name: wait for SSH to come up
  delegate_to: "{{ item.public_ip }}"
  wait_for_connection:
          delay: 60
          timeout: 600
  with_items: "{{ web.instances }}"  
