- name: Deploy App emoji-search on dev server on AWS
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  gather_facts: true
  tasks:
          - include: /etc/ansible/prudential/deployment/tasks/deployment.yml
