- name: Install Java and Jenkins
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ec2-user
  gather_facts: true
  tasks:
       - include: /etc/ansible/prudential/jenkins/tasks/javaInstall.yml
       - include: /etc/ansible/prudential/jenkins/tasks/jenkins.yml
