---
# tasks file for jenkins
- name: upgrade all the packages
  apt:
       update_cache: yes


- name: Ensure java is installed
  apt:
       name: openjdk-8-jdk
       state: latest
       install_recommends: no
