---
# tasks file for jenkins
- name: upgrade all the packages
  yum:
      name: '*'
      state: latest

- name: Ensure java is installed
  package:
       name: java-1.8.0-openjdk
       state: present
